#!/bin/sh

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/txt/emoji | dmenu -i -nb "#000000" -nf "#bbbbbb" -sb "#9400d3" -sf "#eeeeee" -h 30 -l 3 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

echo "$chosen" | tr -d '\n' | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
