add_newline = true

[character]                            
success_symbol = "[Î»](bold cyan)"     

[cmd_duration]
show_milliseconds = false
style = "bold green"
show_notifications = false
min_time_to_notify = 30_000

[directory]
style = "bold purple"
read_only_style = "red"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold #F58FE9"
truncation_symbol = "... "

[git_commit]
only_detached = false
style = "bold yellow"
format = "[$hash]($style) [$tag]($style) "
tag_disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
#format = '\[[$ahead](bold blue)[$added](bold blue) [$modified](bold green) [$untracked](bold cyan)\]'
conflicted = "=$count"
ahead = "â‡¡$count"
behind = "â‡£$count"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?$count"
stashed = "*$count"
modified = "~$count"
staged = "+$count"
renamed = "Â»$count"
deleted = "âœ˜$count"
style = "bold blue"

[golang]
format = "[$symbol ($version)]($style)"
version_format = "${raw} "
symbol = "î˜§"
style = "bold cyan"

[java]
format = "[${symbol}(${version} )]($style)" 
version_format = "${raw}"
style = "red dimmed"

[hostname]
style = "bold dimmed yellow"

[jobs]
symbol = "&"
style = "bold yellow"

[julia]
style = "bold purple"

[line_break]
disabled = false

[memory_usage]
format = "Mem $symbol [${ram}( | Swap ${swap})]($style) "
symbol = ""
disabled = false
threshold = 50 

[nodejs]
format = "[$symbol($version )]($style)"
version_format = "$raw"
style = "bold green"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = "$raw"
symbol = "îˆµ "
style = "yellow"

[rust]
format = "[$symbol($version )]($style)"
version_format = "${raw}"
symbol = "îž¨ ðŸ¦€ "
style = "bold red"

[package]
disabled = true

[status]
disabled = true

[nix_shell]
format = 'via [$name](bold blue) $symbol'
disabled = false
impure_msg = '[$name](bold red)'
pure_msg = '[pure shell](bold green)'
# unknown_msg = '[unknown shell](bold yellow)'
style = "bold blue"

[swift] 
disabled = false

# [custom.timetrace]
# command = """timetrace status --format "Current project: {project} - Worked today: {trackedTimeToday}""""
# when = "timetrace status"
# shell = "sh"

# starship prompt modules */
format = """
$username
$battery
$cmd_duration
$directory
$hostname
$jobs
$memory_usage
$status
$swift

$git_branch
$git_commit 
$git_metrics

$cmake
$conda
$deno
$golang
$java
$julia
$nodejs
$python
$rust

$nix_shell

$character"""
# ${custom.timetrace}
