-- -- THIS PLUGIN LIST SHOULD BE GENERATED BY YOUR NIX CONFIG. See the NixOS Configuration section for more details on plugins table and lazy_nix_helper_path
-- local plugins = {
--     ["nvim-telescope/telescope.nvim "] = "/nix/store/p2znxnhf136gr70mr297qxn27dvs3nvf-lua5.1-telescope.nvim-2024-02-15"
--    }
   
--    local lazy_nix_helper_path = "/nix/store/fjscvcq39x1zbq8v59wr2fs6jf9vpmkn-vimplugin-lazy-nix-helper.nvim "
   
--    -- if we are not on a nix-based system, bootstrap lazy_nix_helper in the same way lazy is bootstrapped
--    if not vim.loop.fs_stat(lazy_nix_helper_path) then
--      lazy_nix_helper_path = vim.fn.stdpath("data") .. "/lazy_nix_helper/lazy_nix_helper.nvim"
--      if not vim.loop.fs_stat(lazy_nix_helper_path) then
--        vim.fn.system({
--          "git",
--          "clone",
--          "--filter=blob:none",
--          "https://github.com/b-src/lazy_nix_helper.nvim.git",
--          lazy_nix_helper_path,
--        })
--      end
--    end
   
--    -- add the Lazy-Nix-Helper plugin to the vim runtime
--    vim.opt.rtp:prepend(lazy_nix_helper_path)
   
--    -- call the Lazy-Nix-Helper setup function. pass a default lazypath for non-nix systems as an argument
--    local non_nix_lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
--    require("lazy-nix-helper").setup({ lazypath = non_nix_lazypath, input_plugin_table = plugins })
   
--    -- get the lazypath from Lazy-Nix-Helper
--    local lazypath = require("lazy-nix-helper").lazypath()
--    -- the rest of the configuration is unchanged
--    if not vim.loop.fs_stat(lazypath) then
--      vim.fn.system({
--        "git",
--        "clone",
--        "--filter=blob:none",
--        "https://github.com/folke/lazy.nvim.git",
--        "--branch=stable", -- latest stable release
--        lazypath,
--      })
--    end
--    -- add the Lazy plugin to the vim runtime
--    vim.opt.rtp:prepend(lazypath)
   
--    -- set mapleader before loading lazy if applicable
--    vim.g.mapleader = " "
   
--    -- install and load plugins from your configuration
--    print(plugins)
--    require("lazy").setup(plugins, opts)