#!/bin/sh

# exec xautolock -detectsleep -time 1 -locker "/home/atarbinian/.local/bin/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking in 30 seconds" &

exec xidlehook --not-when-fullscreen --not-when-audio --timer 60 "systemctl suspend" -
