#!/bin/sh

exec xautolock -detectsleep -time 1 -locker "/home/atarbinian/.local/bin/lock" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

exec xidlehook --not-when-fullscreen --not-when-audio --timer 1200 "systemctl suspend" -
